--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jasson44/SimpleGift
build-by-default: true
branches:
- main
projects:
  SimpleGift:
    path: ""
    icon: "resources/icon.png"
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.0
    lint:
      phpstan: false
...
