name: SimpleGift
version: 1.0.0
main: xeonch\gift\Main
api: 5.0.0
src-namespace-prefix: xeonch\gift
author: XeonCh

permissions:
  xeonch.command.gift:
    description: "Allows the use of the `/gift` command"
    default: true
