name: SimpleGift
version: 1.0.0
main: xeonch\gift\Main
api: 5.0.0
src-namespace-prefix: xeonch\gift
author: XeonCh

permissions:
  simplegift.command:
    description: "Allows the use of the `/simplegift` command"
    default: true
